### ISSUE TITLE
Net::HTTP is not loaded on FFMPEG::Movie

### ISSUE THREAD

**Issue by dineshsprabu** [streamio/streamio-ffmpeg#171]
Hi,

FFMPEG::Movie.new(remote_path) is throwing the below exception with the remote files.
===================
NameError: uninitialized constant FFMPEG::Movie::SocketError
Did you mean?  KeyError
	from /Users/user/.rvm/gems/ruby-2.3.3/gems/streamio-ffmpeg-3.0.2/lib/ffmpeg/movie.rb:251:in `rescue in head'
	from /Users/user/.rvm/gems/ruby-2.3.3/gems/streamio-ffmpeg-3.0.2/lib/ffmpeg/movie.rb:235:in `head'
	from /Users/user/.rvm/gems/ruby-2.3.3/gems/streamio-ffmpeg-3.0.2/lib/ffmpeg/movie.rb:19:in `initialize'
	from (irb):3:in `new'
	from (irb):3
===================

I have resolved the problem by loading 'net/http' explicitly on my code, also noticed that https://github.com/streamio/streamio-ffmpeg/blob/master/lib/ffmpeg/movie.rb in master has already got the fix by adding - require 'net/http'.

Can you please push it to rubygems?

Thanks,
Dinesh.

**Comment by abinashpa** [comment]
I think this project is not maintained now but the `require ' net/http'` helps the issue.
