### ISSUE TITLE
No such file or directory (when file exists)

### ISSUE THREAD

**Issue by colewinans** [streamio/streamio-ffmpeg#71]
For some reason, when trying to transcode a video file (that does really exist), FFMPEG says the file does not exist.

Here's some output from the Rails console, demonstrating my headache:

```
    1.9.3p125 :001 > File.exist?("/Applications/MAMP/htdocs/video-app/public/uploads/tmp/20131208-1416-1234-0984/videotest.mp4")
    => true 

    1.9.3p125 :002 > FFMPEG::Movie.new("/Applications/MAMP/htdocs/video-app/public/uploads/tmp/20131208-1416-1234-0984/videotest.mp4")
    Errno::ENOENT: No such file or directory - ffmpeg -i /Applications/MAMP/htdocs/video-app/public/uploads/tmp/20131208-1416-1234-0984/videotest.mp4
    from /Users/my-comp/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open3.rb:202:in `spawn'
    from /Users/my-comp/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open3.rb:202:in `popen_run'
    from /Users/my-comp/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/open3.rb:90:in `popen3'
    from /Users/my-comp/.rvm/gems/ruby-1.9.3-p125@video-app/gems/streamio-ffmpeg-1.0.0/lib/ffmpeg/movie.rb:17:in `initialize'
    from (irb):2:in `new'
    from (irb):2
    from /Users/my-comp/.rvm/gems/ruby-1.9.3-p125@video-app/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
    from /Users/my-comp/.rvm/gems/ruby-1.9.3-p125@video-app/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
    from /Users/my-comp/.rvm/gems/ruby-1.9.3-p125@video-app/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>    '
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
    1.9.3p125 :003 > 
```

**Comment by coderawal** [comment]
I'm too facing same error after deploying to server but runs fine in my local machine, how can we solve this, is this issue fixed or should i try other than ffmpeg... My machine is Ubuntu 14.04 with ruby 2.1.2 and rails 4.1.5.

**Comment by emmamh** [comment]
Hi. I am also having the same issue trying to concatenate .mp4 files with the Demuxer. These files definitely exist but it's saying they don't or are impossible to open. I have made my .txt file using the file paths that Terminal itself gave me for the .mp4 files and here's what happens:
My-Mac-Pro:~ Me$ ffmpeg -f concat -i /Users/Me/Documents/Dance\ Afire/20150609/Cam1/Cam1.txt -c copy /Users/Me/Documents/Dance\ Afire/20150609/Cam1/Cam1A.mp4
ffmpeg version 2.6.3 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.6.3 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[concat @ 0x7fae9180da00] Impossible to open '/Users/Me/Documents/Dance Afire/20150609/Cam1/‘/Users/Me/Documents/Dance Afire/20150609/Cam1/GOPR0935.MP4’'
/Users/Me/Documents/Dance Afire/20150609/Cam1/Cam1.txt: No such file or directory

**Comment by emmamh** [comment]
(oh and I'm on a Mac, OS X 10.10.1)

**Comment by dreikanter** [comment]
Any news here? I'm facing the same issue apparently.
